# Generated by Django 2.2.7 on 2019-12-22 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('timings', models.CharField(max_length=50)),
                ('subjects', models.CharField(max_length=50)),
                ('classes_taught', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('class_frequency', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
