# Generated by Django 2.1.1 on 2018-09-22 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restrocrud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='restrocrud.Restaurant'),
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restrocrud.Restaurant'),
        ),
    ]
