# Generated by Django 2.1.1 on 2018-10-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerInfo', '0002_auto_20181029_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerAge',
            field=models.IntegerField(),
        ),
    ]
